package be.vives.pizzastore.integration;

import be.vives.pizzastore.client.OpenFoodFactsClient;
import be.vives.pizzastore.controller.CustomerController;
import be.vives.pizzastore.controller.OrderController;
import be.vives.pizzastore.controller.PizzaController;
import be.vives.pizzastore.exception.GlobalExceptionHandler;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.ApplicationContext;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Smoke test: does the whole application context start? Catches wrong wiring, missing beans, bad
 * properties or a broken JPA mapping in one second, before any real test runs.
 * {@code webEnvironment = MOCK} (the default) means no server is started.
 */
@SpringBootTest
class ApplicationSmokeTest {

    @Autowired
    private ApplicationContext context;

    @Test
    void contextLoads_WithAllLayers() {
        assertThat(context.getBean(PizzaController.class)).isNotNull();
        assertThat(context.getBean(CustomerController.class)).isNotNull();
        assertThat(context.getBean(OrderController.class)).isNotNull();
        assertThat(context.getBean(GlobalExceptionHandler.class)).isNotNull();
        assertThat(context.getBean(OpenFoodFactsClient.class)).isNotNull();   // the proxy generated by @ImportHttpServices
    }
}
