package be.vives.pizzastore.mapper;

import be.vives.pizzastore.domain.NutritionalInfo;
import be.vives.pizzastore.domain.Pizza;
import be.vives.pizzastore.dto.request.CreatePizzaRequest;
import be.vives.pizzastore.dto.request.NutritionalInfoRequest;
import be.vives.pizzastore.dto.request.UpdatePizzaRequest;
import be.vives.pizzastore.dto.response.PizzaResponse;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.junit.jupiter.SpringJUnitConfig;

import java.math.BigDecimal;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * The smallest possible "Spring" test: a context with only the two MapStruct implementations that are
 * needed, not the whole application. {@code PizzaMapperImpl} is generated by MapStruct and injects
 * {@code NutritionalInfoMapper}, so both are registered.
 */
@SpringJUnitConfig({PizzaMapperImpl.class, NutritionalInfoMapperImpl.class})
class PizzaMapperTest {

    @Autowired
    private PizzaMapper pizzaMapper;

    @Test
    void toResponse_MapsEntityIncludingNutritionalInfo() {
        Pizza pizza = new Pizza("Margherita", new BigDecimal("8.50"), "Classic");
        pizza.setId(1L);
        pizza.setNutritionalInfo(new NutritionalInfo(266, new BigDecimal("11.0"), new BigDecimal("33.0"), new BigDecimal("10.0")));

        PizzaResponse response = pizzaMapper.toResponse(pizza);

        assertThat(response.id()).isEqualTo(1L);
        assertThat(response.name()).isEqualTo("Margherita");
        assertThat(response.price()).isEqualByComparingTo("8.50");
        assertThat(response.nutritionalInfo().calories()).isEqualTo(266);
    }

    @Test
    void toEntity_MapsRequestAndIgnoresId() {
        CreatePizzaRequest request = new CreatePizzaRequest("Diavola", new BigDecimal("12.99"), "Spicy", true,
                new NutritionalInfoRequest(310, new BigDecimal("14.0"), new BigDecimal("36.0"), new BigDecimal("13.0")));

        Pizza pizza = pizzaMapper.toEntity(request);

        assertThat(pizza.getId()).isNull();
        assertThat(pizza.getName()).isEqualTo("Diavola");
        assertThat(pizza.getAvailable()).isTrue();
        assertThat(pizza.getNutritionalInfo().getCalories()).isEqualTo(310);
    }

    @Test
    void updateEntity_OverwritesFieldsButKeepsId() {
        Pizza existing = new Pizza("Old name", new BigDecimal("5.00"), "Old");
        existing.setId(7L);
        UpdatePizzaRequest update = new UpdatePizzaRequest("New name", new BigDecimal("6.00"), "New", false, null);

        pizzaMapper.updateEntity(update, existing);

        assertThat(existing.getId()).isEqualTo(7L);
        assertThat(existing.getName()).isEqualTo("New name");
        assertThat(existing.getPrice()).isEqualByComparingTo("6.00");
        assertThat(existing.getAvailable()).isFalse();
    }
}
